site_name: AI Interview Q&A - Learn By Doing 369
site_description: 'AI/ML/DL interview preparation with practical questions and concepts'
site_url: 'https://learn-by-doing-369.github.io/AI-Interview-Q-A/'

nav:
  - Home: index.md
  - Machine Learning: Machine_Learning_QA.ipynb
  - Deep Learning: Deep_Learning_QA.ipynb

plugins:
  - mkdocs-jupyter
  - search

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
